server:
  port: 8080
spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: api_route
        uri: http://localhost:8081
        predicates:
        - Path=/skillmgr/api/**
        filters:
        - RewritePath=/skillmgr/api/(?<path>.*), /skillmgr/api/$\{path}
        - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: ui_route
        uri: http://localhost:3000
        predicates:
        - Path=/skillmgr/ui/**
        filters:
        - RewritePath=/skillmgr/ui/(?<path>.*), /skillmgr/ui/$\{path}
    service-registry:
      auto-registration:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.giraffe.mydns.jp/auth/realms/dev.app.sunarch.co.jp
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak: 
#            client-id: gateway
#            client-secret: 244cc4e8-23d9-43ca-a8d9-f7afcff73b15
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorizationGrantType: authorization_code
#            scope: openid,email,profile,roles
#            client-name: gateway
#        provider:
#          keycloak:
#            tokenUri: https://keycloak.giraffe.mydns.jp/auth/realms/dev.app.sunarch.co.jp/protocol/openid-connect/token
#            authorizationUri: https://keycloak.giraffe.mydns.jp/auth/realms/dev.app.sunarch.co.jp/protocol/openid-connect/auth
#            jwkSetUri: https://keycloak.giraffe.mydns.jp/auth/realms/dev.app.sunarch.co.jp/protocol/openid-connect/certs
#            userInfoUri: https://keycloak.giraffe.mydns.jp/auth/realms/dev.app.sunarch.co.jp/protocol/openid-connect/userinfo
#            userNameAttribute: preferred_username
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    jp.co.sunarch.gateway: DEBUG
  file: logs/${spring.application.name}.log
