server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: api_route
        uri: lb://skillMgrApi
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<path>.*), /api/$\{path}
      - id: ui_route
        uri: lb://skillMgrUi
        predicates:
        - Path=/ui/**
        filters:
        - RewritePath=/ui/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
logging:
  level:
    root: INFO
    jp.co.sunarch.gateway: DEBUG
  file: logs/${spring.application.name}.log
